; CREATE TRIANGLE WITH ASTERISK
TITLE PARCIAL4_FIGURA1
INCLUDE IRVINE32.INC
;@AUTHOR: GABRIELA DOMINGUEZ HERNANDEZ
;@COUNTRY: EL SALVADOR, CENTRO AMERICA
.DATA
	ALUM_NAME BYTE " NOMBRE: GABRIELA DOMINGUEZ HERNANDEZ", 0
	ALUM_CRNT BYTE " COUNTRY: EL SALVADOR",0
.CODE
	AGUACATE PROC
		CALL CLRSCR
		;DATOS ALUMNA
		CALL CRLF
		MOV EDX, OFFSET ALUM_NAME
		CALL WRITESTRING
		CALL CRLF
		MOV EDX, OFFSET ALUM_CRNT
		CALL WRITESTRING
		CALL CRLF
		CALL CRLF
		MOV ECX, 0
		
		MOV EBX, 1		;INICIALIZANDO EBX CON 1
		MIENTRAS: CMP EBX, 10	
				  JBE BUCLE1			; EBX <=10
				  JA FINMIENTRAS_BUCLE1	; EBX > 10
				  
			;CONTENIDO DEL BUCLE 1
			BUCLE1: MOV ECX, 10					;INICIANDO ECX CON 10
					MIENTRAS2: CMP ECX, 1
							   JAE BUCLE2				; ECX >= 1
							   JB FINMIENTRAS_BUCLE2	; ECX < 1
						;CONTENIDO BUCLE 2
						BUCLE2: CMP EBX, ECX
								JBE SI_TRUE		; EBX <= ECX 
								JA SINO			;NO SE CUMPLIO
								;IF
								SI_TRUE: MOV AL, BYTE PTR "*"
										JMP FUERA_IF
								;ELSE	
								SINO: MOV AL, BYTE PTR " "
										JMP FUERA_IF
										
								FUERA_IF: CALL WRITECHAR	
										  DEC ECX
										  JMP MIENTRAS2
											
					FINMIENTRAS_BUCLE2:CALL CRLF
									INC EBX	
									JMP MIENTRAS

		FINMIENTRAS_BUCLE1: EXIT
		CALL CRLF
	AGUACATE ENDP
	END AGUACATE