; CREATE X WITH ASTERISK
TITLE PARCIAL4_FIGURA2
INCLUDE IRVINE32.INC
;@AUTHOR: GABRIELA DOMINGUEZ HERNANDEZ
;@COUNTRY: EL SALVADOR, CENTRO AMERICA
.DATA
	ALUM_NAME BYTE " NOMBRE: GABRIELA DOMINGUEZ HERNANDEZ", 0
	ALUM_CRNT BYTE " COUNTRY: EL SALVADOR",0
.CODE
	TORTILLA PROC
		CALL CLRSCR
		;DATOS ALUMNA
		CALL CRLF
		MOV EDX, OFFSET ALUM_NAME
		CALL WRITESTRING
		CALL CRLF
		MOV EDX, OFFSET ALUM_CRNT
		CALL WRITESTRING
		CALL CRLF
		CALL CRLF
		MOV EDX, 1			;	INICIALIZANDO EDX CON 1
		MIENTRAS_FILAS: CMP EDX, 6
						JBE MIENTRAS_COLUM		;	EDX <= 6
						JA FINMIENTRAS_FILA		;	EDX > 6
						
					MIENTRAS_COLUM:	MOV ECX, 1			;	INICIALIZANDO ECX CON 1
						COLUMNAS:CMP ECX, 6
								JBE ACCIONES			;	ECX <= 6
								JA FINMIENTRAS_COLUM	;	ECX > 6
										
								ACCIONES:MOV AL, BYTE PTR " "	
										MOV EBX, EDX
										CMP EDX, ECX
										JE IF_TRUE		; EBX = ECX
										JMP CONTINUA	; NO SE CUMPLIO
								
								IF_TRUE: MOV AL, BYTE PTR "*"	;CONTENIDO 1ER. IF
										JMP CONTINUA
										
								CONTINUA:MOV EBX, 7
										SUB EBX, EDX
										CMP EBX, ECX
										JE ACCIONES_IF2	;	EBX == ECX
										JMP CONTINUA2	; NO SE CUMPLIO
										
										ACCIONES_IF2: MOV AL, BYTE PTR "*"	;CONTENIDO 2DO. IF
													JMP CONTINUA2
								;INCREMENTANDO ECX DEL 2DO. MIENTRAS	
						CONTINUA2: CALL WRITECHAR
									INC ECX
									JMP COLUMNAS
							;INCREMENTANDO EDX DEL 1ER. MIENTRAS	
					FINMIENTRAS_COLUM: CALL CRLF
										INC EDX
										JMP MIENTRAS_FILAS
		FINMIENTRAS_FILA: EXIT
		CALL CRLF
	TORTILLA ENDP
	END TORTILLA	