;STATEMENT: Find the number of vowels that a string contains.

TITLE PRUEB_CONTAR_VOCALES
;@AUTHOR: GABRIELA DOMINGUEZ HERNANDEZ
;@COUNTRY: EL SALVADOR, CENTRO AMERICA
INCLUDE IRVINE32.INC
INCLUDE MACROS.INC
	;MACROS	
	mMAIN_COUNT_VOCALS MACRO LETRAS
	.DATA
		COUNT DWORD 0 
	.CODE
		;;CALL WRITEDEC
		MOV ESI, OFFSET LETRAS
		REPETIR: 
		MOV AL, [ESI]
		.IF(AL=="A" ||AL=="E" ||AL=="I" ||AL=="O" ||AL=="U" ||AL=="a" ||AL=="e" ||AL=="i" ||AL=="o" ||AL=="u")
			;;
		.ELSE
			.IF(AL==0)
				JMP SALIR
			.ELSE
				ADD COUNT,1
			.ENDIF
		.ENDIF
		INC ESI
		JMP REPETIR
		SALIR:
		CALL CRLF
		mWrite "CANTIDAD DE VOCALES: "
		MOV EAX, COUNT
	ENDM
	
	.DATA
		TEXT BYTE "INGRESE TEXTO A EVALUAR: ",0
		L1 BYTE 30 dup(0)
	.CODE
		ARROZ PROC
			CALL CLRSCR
			CALL CRLF
			mWrite " NOMBRE: GABRIELA HERNANDEZ"
			CALL CRLF
			mWrite " COUNTRY: EL SALVADOR"
			CALL CRLF
			CALL CRLF
			MOV EDX,OFFSET TEXT
			CALL WRITESTRING
			MOV EDX , OFFSET L1
			MOV ECX , SIZEOF L1
			CALL READSTRING
			; INVOKE MACRO
			mMAIN_COUNT_VOCALS L1
			CALL WRITEDEC
			CALL CRLF
			EXIT
		ARROZ ENDP
	END ARROZ