;STATEMENT: Multiplication with successive sums.

TITLE COCO
;@AUTHOR: GABRIELA DOMINGUEZ HERNANDEZ
;@COUNTRY: EL SALVADOR, CENTRO AMERICA
INCLUDE IRVINE32.INC
INCLUDE MACROS.INC
	;MACROS
	mSUCCESSIVE_SUMS MACRO NUM1:REQ, NUM2:=<0>
		.DATA
			
		.CODE
			MOV EAX,NUM1
			MOV ECX, 1
			SUCESIVO: CMP ECX, NUM2
					JB BUCLE	;; <
					JAE FINBUCLE	;; >
					
					BUCLE: ADD EAX, NUM1
							INC ECX
							;;CALL CRLF
							;;CALL WRITEDEC
							JMP SUCESIVO
							
					FINBUCLE: ;CALL WRITEDEC
							;EXIT
	ENDM	

	.DATA
		V1 DWORD 0
		V2 DWORD 0
		MEN1  BYTE " INGRESE EL PRIMER NUMERO: ",0
		MEN2  BYTE " INGRESE EL SEGUNDO NUMERO: ",0
	.CODE
		MINUTA PROC
			CALL CLRSCR
			CALL CRLF
			mWrite " NOMBRE: GABRIELA HERNANDEZ"
			CALL CRLF
			mWrite " COUNTRY: EL SALVADOR"
			CALL CRLF
			CALL CRLF
			
			MOV EDX,OFFSET MEN1
		    CALL WRITESTRING	   
		    CALL READDEC
		    MOV V1,EAX
		    ;CALL CRLF
		    MOV EDX,OFFSET MEN2
		    CALL WRITESTRING	 
		    CALL READDEC
		    MOV V2,EAX
		    CALL CRLF
			
			mWrite "LA MULTICACION ES: "
			mSUCCESSIVE_SUMS V1, V2
			CALL WRITEDEC
		MINUTA ENDP
	END MINUTA